import { copyFileSync, existsSync, mkdirSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { basename, dirname, relative, resolve, sep } from 'node:path';
import { pathToFileURL } from 'node:url';

import { z } from 'zod';

import type { PluginIdentity } from '../src/plugin-content';
import { LANDING_ROOT, pluginSources } from './plugin-sources';

const gallerySchema = z.object({
  title: z.string(), description: z.string(),
  items: z.array(z.object({
    id: z.string(), title: z.string(), description: z.array(z.string()),
    mediaSrc: z.string(), mediaAlt: z.string(), mediaLabel: z.string(),
  })),
});
const landingSchema = z.object({
  route: z.string().regex(/^\/apps\/[a-z0-9][a-z0-9-]*$/),
  name: z.string().min(1), shortName: z.string(), description: z.string(),
  features: z.array(z.string()), hasInteractiveDemo: z.boolean(),
  installScreenshot: z.string().nullable(),
  assetAliases: z.array(z.object({ source: z.string(), publicPath: z.string().regex(/^\/screenshots\/[a-z0-9-]+\.(png|jpe?g|gif|svg|webp)$/) })),
  demoStories: z.array(z.object({
    id: z.string(), label: z.string(),
    variants: z.array(z.object({ view: z.enum(['desktop', 'mobile']), src: z.string(), alt: z.string(), durationMs: z.number().positive() })),
  })),
  presentation: z.object({ title: z.string(), description: z.string(), featureGallery: gallerySchema.nullable() }).nullable(),
  roadmapRepoId: z.string().nullable(),
});

type CopyPluginAssetProps = {
  root: string;
  alias: string;
  path: string;
  targetRoot: string;
};

export function copyPluginAsset({ root, alias, path, targetRoot }: CopyPluginAssetProps): void {
  const source = resolve(root, path);
  const pluginRoot = realpathSync(root);

  if (!existsSync(source) || !realpathSync(source).startsWith(`${pluginRoot}${sep}`)) {
    throw new Error(`Missing or out-of-plugin asset for ${alias}: ${path}`);
  }

  const target = resolve(targetRoot, 'plugin-assets', alias, relative(root, source));
  mkdirSync(dirname(target), { recursive: true });
  copyFileSync(source, target);
}

export function copyPluginIconsToLanding(targetRoot: string): void {
  for (const plugin of pluginSources()) {
    if (plugin.icon) {
      copyPluginAsset({ root: plugin.root, alias: plugin.alias, path: plugin.icon, targetRoot });
      // Embedded demo metadata uses the existing flat icon URL convention.
      const target = resolve(targetRoot, 'plugin-icons', plugin.alias, basename(plugin.icon));
      mkdirSync(dirname(target), { recursive: true });
      copyFileSync(resolve(plugin.root, plugin.icon), target);
    }
  }
}

async function generateContent(): Promise<void> {
  const imports: string[] = [];
  const entries: string[] = [];
  const routes = new Set<string>();
  const aliases = new Set<string>();
  const targetRoot = resolve(LANDING_ROOT, 'public');

  // This ignored directory contains only generator-owned copies.
  rmSync(resolve(targetRoot, 'plugin-assets'), { recursive: true, force: true });

  for (const plugin of pluginSources()) {
    const entrypoint = resolve(plugin.root, 'landing.ts');

    if (!existsSync(entrypoint)) {
      throw new Error(`Plugin ${plugin.alias} must export landingPage from landing.ts`);
    }

    const module = await import(pathToFileURL(entrypoint).href);
    const definition = landingSchema.parse(module.landingPage);

    if (routes.has(definition.route)) {
      throw new Error(`Duplicate landing route: ${definition.route}`);
    }

    routes.add(definition.route);
    const assets = [plugin.icon, definition.installScreenshot,
      ...definition.assetAliases.map((asset) => asset.source),
      ...definition.demoStories.flatMap((story) => story.variants.map((variant) => variant.src)),
      ...(definition.presentation?.featureGallery?.items.map((item) => item.mediaSrc) ?? []),
    ];

    for (const path of new Set(assets)) {
      if (path) {
        copyPluginAsset({ root: plugin.root, alias: plugin.alias, path, targetRoot });
      }
    }

    for (const asset of definition.assetAliases) {
      if (aliases.has(asset.publicPath)) {
        throw new Error(`Duplicate asset URL: ${asset.publicPath}`);
      }

      aliases.add(asset.publicPath);
    }

    const name = `plugin${imports.length}`;
    imports.push(`import { landingPage as ${name} } from '../../../../plugins/${plugin.alias}/landing';`);
    const identity: PluginIdentity = { alias: plugin.alias, packageName: plugin.packageName, repo: plugin.repo, icon: plugin.icon };
    entries.push(`  createLandingApp(${name}, ${JSON.stringify(identity)}),`);
  }

  const output = resolve(LANDING_ROOT, 'src/generated/plugin-content.ts');
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, `// Generated by scripts/generate-content.ts. Edit plugin landing.ts sources.\nimport { createLandingApp } from '../plugin-content';\nimport type { LandingApp } from '../../content-types';\n${imports.join('\n')}\n\nexport const officialApps: LandingApp[] = [\n${entries.join('\n')}\n];\n`);
  console.log(`Generated ${entries.length} plugin content entries and copied their assets.`);
}

if (import.meta.main) {
  await generateContent();
}
